import bcrypt from "bcryptjs";
const data = {
  users: [
    {
      name: "Jacob",
      email: "bayisagobu@gmail.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: true,
    },
    {
      name: "Tamirat",
      email: "tamirab1@gmail.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      _id: "1",
      name: "gray nike",
      category: "shoe",
      image: "/images/nikegray.jpg",
      price: 120,
      countInStock: 8,
      brand: "Nike",
      rating: 4.6,
      numReviews: 20,
      description: "high quality  gray nike product",
    },
    {
      _id: "2",
      name: "red nike shoe",
      category: "shoe",
      image: "/images/nikered.jpg",
      price: 100,
      countInStock: 10,
      brand: "NIke",
      rating: 4.0,
      numReviews: 10,
      description: "high quality product. You will like it",
    },
    {
      _id: "3",
      name: "Red High hill shoe",
      category: "shoe",
      image: "/images/redHighhill.png",
      price: 220,
      countInStock: 0,
      brand: "Lacoste",
      rating: 4.8,
      numReviews: 17,
      description: "high quality product",
    },
    {
      _id: "4",
      name: "Flat Sneaker",
      category: "shoe",
      image: "/images/flatsneaker.png",
      price: 78,
      countInStock: 15,
      brand: "London",
      rating: 4.5,
      numReviews: 15,
      description: "high quality modern style flat sneaker",
    },
    {
      _id: "5",
      name: "Golden Mens shoe",
      category: "shoe",
      image: "/images/goldenshoe.jpg",
      price: 95,
      countInStock: 15,
      brand: "Lion",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "6",
      name: "Winter Shoe",
      category: "shoe",
      image: "/images/winterShoe.jpg",
      price: 140,
      countInStock: 14,
      brand: "Adidas",
      rating: 4.3,
      numReviews: 15,
      description: "high quality- pure leather winter shoe",
    },
    {
      _id: "7",
      name: "Durable multi purpose shoe",
      category: "shoe",
      image: "/images/durableBoot.jpg",
      price: 220,
      countInStock: 0,
      brand: "Lacoste",
      rating: 4.8,
      numReviews: 17,
      description: "high quality product",
    },
    {
      _id: "8",
      name: "Durable Torch shoe",
      category: "shoe",
      image: "/images/toarchshoe.jpg",
      price: 190,
      countInStock: 4,
      brand: "Lacoste",
      rating: 4.8,
      numReviews: 11,
      description: "high quality and durable product",
    },
    {
      _id: "9",
      name: "Country style high hill shoe",
      category: "shoe",
      image: "/images/countryStyle.jpg",
      price: 210,
      countInStock: 4,
      brand: "Lacoste",
      rating: 4.8,
      numReviews: 17,
      description: "high quality product with shinining design",
    },
  ],
};
export default data;
