const data = {
    products: [
      {
        _id: '1',
        name: 'gray nike',
        category: 'shoe',
        image: '/images/nikegray.jpg',
        price: 120,
        countInStock: 8,
        brand: 'Nike',
        rating: 4.6,
        numReviews: 20,
        description: 'high quality  gray nike product',
      },
      {
        _id: '2',
        name: 'red nike shoe',
        category: 'shoe',
        image: '/images/nikered.jpg',
        price: 100,
        countInStock: 10,
        brand: 'NIke',
        rating: 4.0,
        numReviews: 10,
        description: 'high quality product. You will like it',
      },
      {
        _id: '3',
        name: 'High hill shoe',
        category: 'shoe',
        image: '/images/highhill.jpg',
        price: 220,
        countInStock: 0,
        brand: 'Lacoste',
        rating: 4.8,
        numReviews: 17,
        description: 'high quality product',
      },
      {
        _id: '4',
        name: 'London high hill',
        category: 'shoe',
        image: '/images/london.jpg',
        price: 78,
        countInStock: 15,
        brand: 'London',
        rating: 4.5,
        numReviews: 15,
        description: 'high quality product',
      },
      {
        _id: '5',
        name: 'Golden Mens shoe',
        category: 'shoe',
        image: '/images/goldenshoe.jpg',
        price: 95,
        countInStock: 15,
        brand: 'Lion',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '6',
        name: 'Off white mens shoe',
        category: 'shoe',
        image: '/images/white.jpg',
        price: 140,
        countInStock: 14,
        brand: 'Adidas',
        rating: 4.3,
        numReviews: 15,
        description: 'high quality- non fading color product',
      },
    ],
  };
  export default data;
  